name: concha
channels:
  - defaults
dependencies:
  - scikit-learn
  - jupyterlab
  - tensorflow
  - pandas
  - seaborn
  - python
  - statsmodels
  - squareup
  - scipy
  - pytz
  - geocoder
  - requests

